version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
  exclusions:
    paths:
      - debug
      - vendor

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
