name: Dependency Update

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    name: Update Go Dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Update dependencies
      id: update
      run: |
        # Get current go.sum hash
        CURRENT_HASH=$(sha256sum go.sum | cut -d' ' -f1)
        echo "current_hash=$CURRENT_HASH" >> $GITHUB_OUTPUT

        # Update all dependencies
        go get -u ./...
        go mod tidy

        # Get new go.sum hash
        NEW_HASH=$(sha256sum go.sum | cut -d' ' -f1)
        echo "new_hash=$NEW_HASH" >> $GITHUB_OUTPUT

        # Check if anything changed
        if [ "$CURRENT_HASH" != "$NEW_HASH" ]; then
          echo "changes_detected=true" >> $GITHUB_OUTPUT
        else
          echo "changes_detected=false" >> $GITHUB_OUTPUT
        fi

    - name: Run tests
      if: steps.update.outputs.changes_detected == 'true'
      run: |
        go test -v $(go list ./... | grep -v '/debug')

    - name: Build check
      if: steps.update.outputs.changes_detected == 'true'
      run: |
        go build -v .

    - name: Create Pull Request
      if: steps.update.outputs.changes_detected == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update Go dependencies'
        title: 'chore: update Go dependencies'
        body: |
          ## Automated Dependency Update

          This PR updates Go dependencies to their latest versions.

          ### Changes
          - Updated all Go modules to latest versions
          - Ran `go mod tidy` to clean up

          ### Testing
          - ✅ All tests pass
          - ✅ Build succeeds

          **Note**: This PR was created automatically by the dependency update workflow.

          Please review the changes before merging.
        branch: automated/dependency-update
        delete-branch: true
        labels: |
          dependencies
          automated